// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrwzizmlybdxkmcijpug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyd3ppem1seWJkeGttY2lqcHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTY0MjQsImV4cCI6MjA3MzY3MjQyNH0.bSNlseRbcivSP0-d1nZn5NwXZsshAQNeM2-ip5Pcnyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});